summary: "Evaluate a call"
description: "Evaluate the call by the engine, means that it will act, reach this endpoint at the end of the phone call\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Engine#evaluate-call"

tags:
- Engine

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - boxid
    - report
    - Call
    properties:
      token:
        type: string
        description: JWT token
      boxid:
        type: string
        description: Box ID
      report:
        type: bool
        description: Does the user reported this number
      Call:
        type: Call
        description: User's password
      Call:
        type: object
        required:
        - number
        - status
        - time
        properties:
          number:
            type: string
            description: Call number
          status:
            type: string
            description: Call status... Missed, Received, Blocked, Outgoing
          time:
            type: integer
            description: Time of the start of the call

responses:
  200:
    description: "Success"
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
