summary: "Get the number of reported number"
description: "Count how many numbers have been reported\n"

tags:
- Engine

produces:
- "application/json"

parameters:
  - name: token
    type: string
    in: query
    required: True
    minimum: 1

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        count:
          type: int
          description: Reported numbers
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  401:
    description: "\"Bad token\""
  403:
    description: "Two cases:\n- There is something wrong with the token, check if the account still exists\n- A report must be sent at the end of a call"
  500:
    description: "Internal Logic Error - Please report all theses errors"
