summary: "Evaluate a call"
description: "Evaluate the call by the engine, means that it will act, reach this endpoint at the end of the phone call\nThis endpoint can only be called at the end of a call\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Engine#evaluate-call"

tags:
- Engine

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - report
    - Call
    properties:
      token:
        type: string
        description: JWT Embedded token
      report:
        type: bool
        description: Does the user reported this number
      Call:
        type: object
        required:
        - number
        - status
        - time
        properties:
          number:
            type: string
            description: Call number
          status:
            type: string
            description: Call status... Missed, Received, Blocked, Outgoing
          time:
            type: integer
            description: Time of the start of the call

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        message:
          type: string
          description: Evaluation Message
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  401:
    description: "\"Bad token\""
  403:
    description: "Two cases:\n- There is something wrong with the token, check if the account still exists\n- A report must be sent at the end of a call"
  500:
    description: "Internal Logic Error - Please report all theses errors"
