kind: pipeline
type: docker
name: deployment

steps:
- name: dev deployment
  image: alpine
  commands:
  - cd deployment
  - docker-compose up -d --force-recreate --no-deps --build magi_dev
  when:
    branch:
    - DEV

- name: prod deployment
  image: alpine
  commands:
  - cd deployment
  - docker-compose up -d --force-recreate --no-deps --build magi_prod
  when:
    branch:
    - master

- name: postman deployment
  image: alpine
  commands:
  - cd deployment
  - docker-compose up -d --force-recreate --no-deps --build magi_postman
  when:
    branch:
    - DEV
    - master
