kind: pipeline
type: docker
name: deployement

steps:

  - name: dev automatic deployement
    image: appleboy/drone-ssh
    volumes:
    - name: ssh_key
      path: /root/ssh/drone
    settings:
      host: safetel.francecentral.cloudapp.azure.com
      ssh_username: backadmin
      key_path: /root/ssh/drone
      # ssh_key:
      #   from_secret: private_ssh_key
      port: 60999
      script:
        - cd devOps/deployement
        - ls
        - docker-compose pull magi_dev
        - docker-compose up -d --force-recreate --no-deps --build magi_dev
      when:
        branch:
        - DEV

volumes:
- name: ssh_key
  host:
    path: /home/backadmin/.ssh/drone-ssh/drone
