version: "3.3"

services:
    magi:
        env_file: ./devOps/dev-config.env
        build:
            context: ./
        ports:
            - 2407:2407
        restart:
            on-failure
        environment:
            SERVER_PORT: 2407
