version: "3.3"

services:
    magi:
        build:
            ./
        ports:
            - 2407:2407
        restart:
            on-failure
        environment:
            - DBName=Melchior
            - DBPassword=aSEFTHUKOM1!
            - MongoAtlasClusterURI=mongodb+srv://SafeTelBackEndUser:aSEFTHUKOM1!@safetel-back-cluster.klq5k.mongodb.net/Melchior?retryWrites=true&w=majority

