version: "3.3"

services:
    magi:
        build:
            context: ./
            args:
                SECRET_KEY: ${SECRET_KEY}
        ports:
            - 2407:2407
        restart:
            on-failure
        environment:
            SERVER_PORT: 2407
