summary: "Update Box's severity"
description: "Update Box's severity\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints%3A-Box#update-severity"

tags:
- Box

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - boxid
    - severity
    properties:
      token:
        type: string
        description: JWT token
      boxid:
        type: string
        description: Box's ID
      severity:
        type: string
        description: Box's severity

responses:
  200:
    description: "Success"
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
