summary: "Get the server's condition"
description: "Get the server's condition from an Admin or Dev account\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Embedded#box-infos"

tags:
- InternalDev

produces:
- "application/json"

parameters:
  - name: token
    type: string
    in: query
    required: True
    minimum: 1

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        healthCheck:
          type: object
          properties:
            server:
              type: object
            environment:
              type: object
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  401:
    description: "\"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
