version: "3.3"

services:
    drone_server:
        # container_name: drone_server
        image: 
            drone/drone:latest
        ports:
            - 80:80
            - 443:443
        environment:
            - DRONE_GITHUB_CLIENT_ID=4d2a8308db5b980cd4ee
            - DRONE_GITHUB_CLIENT_SECRET=899c6ccd61d18cef732e6d2cd189aea11614bc3e
            - DRONE_RPC_SECRET=5db786fafec54ea081651b3ed7a68692
            - DRONE_SERVER_HOST=safetel.francecentral.cloudapp.azure.com
            - DRONE_SERVER_PROTO=https
            - DRONE_TLS_AUTOCERT=true
            - DRONE_USER_CREATE=username:safetel,admin:true

            # - DRONE_GIT_ALWAYS_AUTH=true
            # - DRONE_GIT_USERNAME=
            # - DRONE_GIT_PASSWORD=

        volumes:
            - /var/lib/drone:/data
        restart: always

    drone_runner:
    # container_name: drone_runner
        depends_on:
            - "drone_server"
        image:
            drone/drone-runner-docker:latest
        ports:
            - 3000:3000
        environment:
            - DRONE_RPC_PROTO=https
            - DRONE_RPC_HOST=safetel.francecentral.cloudapp.azure.com
            - DRONE_RPC_SECRET=5db786fafec54ea081651b3ed7a68692 
            - DRONE_RUNNER_CAPACITY=2
            - DRONE_RUNNER_NAME=safetel-drone-runner
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        restart: always