summary: "Reverse the evaluation"
description: "Reverse an evlauation for the given number (also any action due to evaluyate-call other than history)\n"

tags:
- Embedded

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - boxid
    - number
    properties:
      token:
        type: string
        description: JWT token
      boxid:
        type: string
        description: Box's ID
      nummber:
        type: string
        description: Phone number of the report to reverse

responses:
  200:
    description: "Success"
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
