summary: "Embedded OTA avaibality"
description: "Embedded OTA avaibality\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Embedded#update"

tags:
- Embedded

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - version
    properties:
      version:
        type: float
        description: Box's version

responses:
  200:
    description: "Success"
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
