summary: "Box's login"
description: "Login from a Box ID\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Embedded#login-box"

tags:
- Embedded

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - boxid
    properties:
      boxid:
        type: string
        description: Box's ID

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        token:
          type: string
          description: Box token
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
