summary: "Reset the password from email"
description: "Send an email with a reset password link\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints%3A-Authentification.LostPassword#update-lost-password"

tags:
- Authentification.LostPassword

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - password
    properties:
      token:
        type: string
        description: JWT token
      password:
        type: string
        description: New user's password

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        passwordupdated:
          type: boolean
          description: The status of the password update
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  401:
    description: "\"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
