summary: "Reset the password from email"
description: "Send an email with a reset password link\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints%3A-Authentification.LostPassword#reset-password"

tags:
- Authentification.LostPassword

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - email
    properties:
      email:
        type: string
        description: Email of the user

responses:
  200:
    description: "Success"
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
