summary: "Register a user"
description: "Register a user\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints%3A-Authentification#register"

tags:
- Authentification

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - magicnumber
    - email
    - username
    - password
    - CustomerInfos
    - Localization
    properties:
      magicnumber:
        type: integer
        description: Magic number
      email:
        type: string
        description: User's email
      username:
        type: string
        description: User's name
      password:
        type: string
        description: User's password
      CustomerInfos:
        type: object
        required:
        - firstName
        - lastName
        - phoneNumber
        properties:
          firstName:
            type: string
            description: User's First Name
          lastName:
            type: string
            description: User's Last Name
          phoneNumber:
            type: string
            description: User's Phone Number
      Localization:
        type: object
        required:
        - country
        - region
        - address
        properties:
          country:
            type: string
            description: User's Country
          region:
            type: string
            description: User's Region
          address:
            type: string
            description: User's Address

responses:
  200:
    description: "Success"
  400:
    description: "Three cases:\n- Missing body values\n- \"Bad token\"\n- This email is already linked to an account"
  500:
    description: "Internal Logic Error - Please report all theses errors"
