summary: "Claim a Box"
description: "Claim a Box from Box's ID for an authenticated user\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints%3A-Box.Link#claim-box"

tags:
- Box.Link

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - boxid
    properties:
      token:
        type: string
        description: JWT token
      boxid:
        type: string
        description: Box's ID

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        linked:
          type: boolean
          description: The status of the linkage
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  401:
    description: "\"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
