summary: "Get the Black & White list of a user"
description: "Get the Black & White list of an authentificated user\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints%3A-Greylist#get-greylist"

tags:
- Account.Lists

produces:
- "application/json"

parameters:
  - name: token
    type: string
    in: query
    required: True
    minimum: 1

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        Blacklist:
          type: array
          items:
            type: string
        Whitelist:
          type: array
          items:
            type: string
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  401:
    description: "\"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
