summary: "Update the personal informations of a user"
description: "Update the personal informations of an authentificated user\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Account.Infos#update-infos"

tags:
- Account.Infos

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - CustomerInfos
    - Localization
    properties:
      token:
        type: string
        description: JWT token
      CustomerInfos:
        type: object
        required:
        - firstName
        - lastName
        - phoneNumber
        properties:
          firstName:
            type: string
            description: User's First Name
          lastName:
            type: string
            description: User's Last Name
          phoneNumber:
            type: string
            description: User's Phone Number
      Localization:
        type: object
        required:
        - country
        - region
        - address
        properties:
          country:
            type: string
            description: User's Country
          region:
            type: string
            description: User's Region
          address:
            type: string
            description: User's Address

responses:
  200:
    description: "Success"
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
