summary: "Update the email of a user"
description: "Update the email of an authentificated user\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Account.Infos#update-email"

tags:
- Account.Infos

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - email
    properties:
      token:
        type: string
        description: JWT token
      email:
        type: string
        description: New Email

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        updated:
          type: boolean
          description: The status of the update
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  401:
    description: "\"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
