summary: "Get the information of a user"
description: "Get the information of an authentificated user\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Account.Infos#get-infos"

tags:
- Account.Infos

produces:
- "application/json"

parameters:
  - name: token
    type: string
    in: query
    required: True
    minimum: 1

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        email:
          type: string
          description: User email
        username:
          type: string
          description: User name
        CustomerInfos:
          type: object
          properties:
            firstName:
              type: string
              description: User's First Name
            lastName:
              type: string
              description: User's Last Name
            phoneNumber:
              type: string
              description: User's Phone Number
        Localization:
          type: object
          properties:
            country:
              type: string
              description: User's Country
            region:
              type: string
              description: User's Region
            address:
              type: string
              description: User's Address
  400:
    description: "Two cases:\n- Missing body values\n- \"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
