summary: "Update the password of a user"
description: "Update the password of an authentificated user\nhttps://github.com/SafeTel/SafeTel-Doc-Backend/wiki/Endpoints:-Account.Infos#update-password"

tags:
- Account.Infos

produces:
- "application/json"

parameters:
- name: Request
  in: body
  schema:
    type: object
    required:
    - token
    - oldpassword
    - newpassword
    properties:
      token:
        type: string
        description: JWT token
      oldpassword:
        type: string
        description: Old Password
      newpassword:
        type: string
        description: New Password

responses:
  200:
    description: "Success"
    schema:
      type: object
      properties:
        updated:
          type: boolean
          description: The status of the update
  400:
    description: "Three cases:\n- Missing body values\n- \"Bad token\"\n- The old and new password are the same"
  401:
    description: "\"Bad token\""
  403:
    description: "There is something wrong with the token, check if the account still exists"
  500:
    description: "Internal Logic Error - Please report all theses errors"
