name: ci-prod

on:
  push:
    branches:
      - 'master'
  pull_request:   # // and pull_request
    branches:
      - 'master'

jobs:
  build: # job_id
    name: pushing new prod docker image on docker hub and deploy # job name
    runs-on: ubuntu-latest # hosted OS
    env:
      PUSH_EVENT: ${{ github.event_name == 'push'}}

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/safetel-back:prod
      - 
        name: executing remote ssh commands for Postman deployment using ssh_key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT_DEV }}
          script: |
            cd /home/backadmin/SafeTel-Back/
            git checkout master
            git pull origin master
            cd devOps/cd/
            docker-compose pull magi_postman
            docker-compose up -d --force-recreate --no-deps --build magi_postman

      - if: ${{ env.PUSH_EVENT }}
        name: executing remote ssh commands for Prod deployment using ssh_key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/backadmin/SafeTel-Back/
            git checkout master
            git pull origin master
            cd devOps/cd/
            docker-compose pull magi_prod
            docker-compose up -d --force-recreate --no-deps --build magi_prod


  postman-build-and-test: # job_id
    name: running postman tests # job name

    runs-on: ubuntu-latest # hosted OS
    strategy:
      matrix:
        node-version: [12.x]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2 # workspace for github action

      - name:  Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install newman # installing newman, CLI to run postman tests
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Build the docker-compose of the project # running docker
        run: docker-compose up -d

      - name: Run POSTMAN collection with DEV env # running POSTMAN tests with postman-env
        run: |
          newman run https://api.getpostman.com/collections/13182887-93e525f5-4a5c-49f5-8fc1-7a4e62bad530?apikey=$API_KEY --environment https://api.getpostman.com/environments/13182887-0b3ed845-907b-418e-a771-70d268e7153d?apikey=$API_KEY
        env:
          API_KEY: ${{secrets.POSTMAN_API_KEY}}
