name: safetel-prod-cd

on:
  push:
    branches:
      - 'master'

jobs:
  build: # job_id
    name: pushing new prod docker image on docker hub and deploy # job name
    runs-on: ubuntu-latest # hosted OS

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/safetel-back:prod

      -
        name: executing remote ssh commands for Prod deployment using ssh_key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/backadmin/SafeTel-Back/
            git checkout master
            git pull origin master
            cd devOps/scripts/
            echo "\n..\n" | bash deploy-magi.sh prod
