name: postman-push-pull-request
on:
  push:           # // this action runs on each new push
    branches:
      - 'master'
  pull_request:   # // and pull_request
    branches:
      - 'master'

jobs:
  postman-build-and-test: # job_id
    name: running postman tests # job name

    runs-on: ubuntu-latest # hosted OS
    strategy:
      matrix:
        node-version: [12.x]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2 # workspace for github action

      - name:  Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install newman # installing newman, CLI to run postman tests
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Build the docker-compose of the project # running docker
        run: docker-compose up -d

      - name: Run POSTMAN collection with PROD env
        run: |
          newman run https://api.getpostman.com/collections/13182887-93e525f5-4a5c-49f5-8fc1-7a4e62bad530?apikey=$API_KEY --environment https://api.getpostman.com/environments/13182887-aaeffc8e-2997-4fde-a21d-ecf08ed7f3db?apikey=$API_KEY
        env:
          API_KEY: ${{secrets.POSTMAN_API_KEY}}