name: postman-push-pull-request
on: [push, pull_request]  # // this action runs on each new push 
                          # // and pull_request

jobs:
  postman-build-and-test: # job_id
    name: running postman tests # job name

    runs-on: ubuntu-latest # hosted OS
    strategy:
      matrix:
        node-version: [12.x]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2 # workspace for github action

      - name:  Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install newman # installing newman, CLI to run postman tests
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Build the docker-compose of the project # running docker
        run: docker-compose up -d

      - name: Run POSTMAN collection with DEV env # running POSTMAN tests with local-env
        run: |
          newman run https://api.getpostman.com/collections/13182887-52e71d5f-5098-4970-8b4a-b756f14bc1b5?apikey=PMAK-61d6d54bc2694e20f2a96297-23580a5c8a31016b8c3a1ba307d106c800 --environment https://api.getpostman.com/environments/13182887-27b5e4d9-672d-46e3-a376-46091c3e8bc5?apikey=PMAK-61d6d54bc2694e20f2a96297-23580a5c8a31016b8c3a1ba307d106c800

      - name: Run POSTMAN collection with PROD env
        run: |
          newman run https://api.getpostman.com/collections/13182887-52e71d5f-5098-4970-8b4a-b756f14bc1b5?apikey=PMAK-61d6d54bc2694e20f2a96297-23580a5c8a31016b8c3a1ba307d106c800 --environment https://api.getpostman.com/environments/13182887-202afc19-c14a-4da2-8ca8-e3cdb3b64f41?apikey=PMAK-61d6d54bc2694e20f2a96297-23580a5c8a31016b8c3a1ba307d106c800
